language: java
sudo: false
install: true
addons:
  chrome: stable
  sonarcloud:
    organization: "blzsaa-github"
    token:
      secure: ${SONAR_TOKEN}
jdk:
  - oraclejdk8
script:
  - mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'