language: java
sudo: false
install: true
addons:
  chrome: stable
  sonarcloud:
    organization: "blzsaa-github"
    token:
      secure: ${SONAR_TOKEN}
jdk:
  - oraclejdk8
before_script:
  -  google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'